apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cassandra
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: cassandra
    spec:
      containers:
        - env:
            - name: CASSANDRA_START_RPC
              value: "true"
            - name: HEAP_NEWSIZE
              value: 128M
            - name: MAX_HEAP_SIZE
              value: 512M
          image: cassandra:4.1
          livenessProbe:
            exec:
              command:
                - cqlsh -e 'DESCRIBE KEYSPACES' 127.0.0.1 9042
            failureThreshold: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
          name: cassandra
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: cassandra-data
      restartPolicy: Always
      volumes:
        - name: cassandra-data
          persistentVolumeClaim:
            claimName: cassandra-data
