apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: chat-web
  name: chat-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: chat-web
    spec:
      containers:
        - image: local/chat-web:latest
          imagePullPolicy: IfNotPresent
          name: chat-web
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
