apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: chat-service
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chat-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: chat-service
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              value: a2594bf00465232dbb9c2d04e76d11745cc1ea216815bacc928ffded234593eb
            - name: MESSAGE_SERVICE_URL
              value: http://message-service:8084
            - name: MYSQL_DSN
              value: root:password@tcp(mysql:3306)/micro_auth?parseTime=true
            - name: REDIS_ADDR
              value: redis:6379
          image: local/chat-service:latest
          imagePullPolicy: IfNotPresent
          name: chat-service
          ports:
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
