apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeforces-api
  labels:
    app: codeforces-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeforces-api
  template:
    metadata:
      labels:
        app: codeforces-api
    spec:
      containers:
        - name: api
          image: local/codeforces-api:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8082"
            - name: DB_DSN
              value: postgres://postgres:orib98wBpwUr15btAqoF2PksuDMTtsfJfrMsnzFUVai2Wo87MzI4SWb1g7cOeakq@micro-postgres.default.svc.cluster.local:5432/postgres?sslmode=require
            - name: MYSQL_DSN
              value: root:password@tcp(mysql.default.svc.cluster.local:3306)/micro_auth?parseTime=true
            - name: KAFKA_BROKERS
              value: kafka.default.svc.cluster.local:9092
            - name: KAFKA_SUBMISSION_TOPIC
              value: cf.submissions
            - name: KAFKA_STATUS_TOPIC
              value: cf.submission_status
            - name: KAFKA_OTP_TOPIC
              value: new-registration
          ports:
            - containerPort: 8082
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
