apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manchik-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/websocket-services: "chat-service,rtc-service,codeforces-api"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chat.manchik.co.uk
        - ws.manchik.co.uk
        - web.manchik.co.uk
        - webrtc.manchik.co.uk
        - turn.manchik.co.uk
        - code.manchik.co.uk
        - codeforces.manchik.co.uk
        - codeforces-api.manchik.co.uk
      secretName: manchik-wildcard
  rules:
    - host: chat.manchik.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registration-api
                port:
                  number: 8082
    - host: ws.manchik.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-service
                port:
                  number: 8083
    - host: web.manchik.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-web
                port:
                  number: 5173
    - host: webrtc.manchik.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rtc-service
                port:
                  number: 8085
    - host: codeforces.manchik.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codeforces-web
                port:
                  number: 3000
    - host: codeforces-api.manchik.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codeforces-api
                port:
                  number: 8082
    - host: turn.manchik.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rtc-service
                port:
                  number: 8085
    - host: code.manchik.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codeforces
                port:
                  number: 8081
