apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: message-service
  name: message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: message-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: message-service
    spec:
      containers:
        - env:
            - name: CASSANDRA_HOSTS
              value: cassandra
            - name: CASSANDRA_KEYSPACE
              value: chat_data
            - name: KAFKA_URL
              value: kafka:9092
            - name: MESSAGE_EVENTS_TOPIC
              value: chat-messages
            - name: SERVICE_PORT
              value: "8084"
          image: local/message-service:latest
          imagePullPolicy: IfNotPresent
          name: message-service
          ports:
            - containerPort: 8084
              protocol: TCP
      restartPolicy: Always
