apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-hba-config
data:
  pg_hba.conf: |
    # Allow node access
    host all all 0.0.0.0/0 md5
    # Allow pod subnet
    host all all 10.0.0.0/8 md5
    # Local connections
    local all all trust

