apiVersion: v1
data:
  AuthKey_3NBGA8639B.p8: |-
    -----BEGIN PRIVATE KEY-----
    MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgFny+XtKxNcYNo0dS
    YeBUJyInNuML4sB8FVqRzh4oM66gCgYIKoZIzj0DAQehRANCAAS4IkkRlga8q4Zc
    acH8/YyP0MhsFfglU3fasJ81MaVpUtQCYhkrvRUKl/BAx+nXVlNSBMr9nRha5nO/
    TXRQMISb
    -----END PRIVATE KEY-----
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: push-service
  name: push-service-cm0
