apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: registration-api
  name: registration-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: registration-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: registration-api
    spec:
      containers:
        - env:
            - name: CORS_ALLOWED_ORIGINS
              value: https://chat.manchik.co.uk,https://web.manchik.co.uk,http://localhost:5173,http://127.0.0.1:5173
            - name: JWT_SECRET
              value: a2594bf00465232dbb9c2d04e76d11745cc1ea216815bacc928ffded234593eb
            - name: KAFKA_URL
              value: kafka:9092
            - name: MESSAGE_SERVICE_URL
              value: http://message-service:8084
            - name: MYSQL_DSN
              value: root:password@tcp(mysql:3306)/micro_auth?parseTime=true
          image: local/registration-api:latest
          imagePullPolicy: IfNotPresent
          name: registration-api
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
