apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: rtc-service
  name: rtc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rtc-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: rtc-service
    spec:
      containers:
        - env:
            - name: CORS_ALLOWED_ORIGINS
              value: https://chat.manchik.co.uk,https://web.manchik.co.uk,http://localhost:5173,http://127.0.0.1:5173
            - name: SERVICE_PORT
              value: "8085"
            - name: SESSION_TTL_SECONDS
              value: "900"
            - name: TURN_CREDENTIAL_TTL
              value: "600"
            - name: TURN_SERVER_URLS
              value: turn:turn.manchik.co.uk:3478?transport=udp,turn:turn.manchik.co.uk:3478?transport=tcp,stun:stun.l.google.com:19302
            - name: TURN_SHARED_SECRET
              value: devsecret
          image: local/rtc-service:latest
          imagePullPolicy: IfNotPresent
          name: rtc-service
          ports:
            - containerPort: 8085
              protocol: TCP
      restartPolicy: Always
